### ISSUE TITLE
Unexpected token y in JSON

### ISSUE THREAD

**Issue by mlenser** [devshorts/ytools#2]
While running `ytools` from the root of a project I get the following message:

```
(node:50753) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token y in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.yarnWorkspaceInfo (/FOLDER/node_modules/yarn-workspace-tools/dist/tools.js:54:28)
    at detect (/FOLDER/node_modules/yarn-workspace-tools/dist/index.js:23:31)
    at Object.<anonymous> (/FOLDER/node_modules/yarn-workspace-tools/dist/index.js:118:1)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

this points to 
```
function yarnWorkspaceInfo() {
    return JSON.parse(JSON.parse(run("yarn workspaces info --json"))["data"]);
}
```

If I run `yarn workspaces info --json` directly it works (it returns an object with each package having an object). It's a bit hard to debug further due to the run command being in tools.js.

Not sure if it's related to our project or how to debug from here.

**Comment by devshorts** [comment]
Can you post a sample of what yarn workspace info json returns for you? What version of yarn are you using?

**Comment by mlenser** [comment]
Yarn 1.21.1

`yarn workspaces info --json`:
```
{"type":"log","data":"{\n  \"@hi3g/3style-docs\": {\n    \"location\": \"packages/3style-docs\",\n    \"workspaceDependencies\": [\n      \"@hi3g/browserslist-config\",\n      \"@hi3g/lint-config\",\n      \"@hi3g/3style\",\n      \"@hi3g/icons\"\n
],\n    \"mismatchedWorkspaceDependencies\": []\n  },\n  \"@hi3g/3style\": {\n    \"location\": \"packages/core/3style\",\n    \"workspaceDependencies\": [\n      \"@hi3g/browserslist-config\",\n      \"@hi3g/lint-config\",\n      \"@hi3g/fonts\",\n
   \"@hi3g/icons\"\n    ],\n    \"mismatchedWorkspaceDependencies\": []\n  },\n  \"@hi3g/analytics\": {\n    \"location\": \"packages/core/analytics\",\n    \"workspaceDependencies\": [\n      \"@hi3g/browserslist-config\",\n      \"@hi3g/lint-config\"
\n    ],\n    \"mismatchedWorkspaceDependencies\": []\n  },\n  \"@hi3g/application-insights\": {\n    \"location\": \"packages/core/application-insights\",\n    \"workspaceDependencies\": [\n      \"@hi3g/lint-config\",\n      \"@hi3g/server-logger\"\n
    ],\n    \"mismatchedWorkspaceDependencies\": []\n  },\n  \"@hi3g/browserslist-config\": {\n    \"location\": \"packages/core/browserslist-config\",\n    \"workspaceDependencies\": [\n      \"@hi3g/lint-config\"\n    ],\n    \"mismatchedWorkspaceDep
endencies\": []\n  },\n  \"@hi3g/logger-dev\": {\n    \"location\": \"packages/core/client-logger/dev\",\n    \"workspaceDependencies\": [],\n    \"mismatchedWorkspaceDependencies\": []\n  },\n  \"@hi3g/client-logger\": {\n    \"location\": \"packages/
core/client-logger\",\n    \"workspaceDependencies\": [\n      \"@hi3g/browserslist-config\",\n      \"@hi3g/lint-config\"\n    ],\n    \"mismatchedWorkspaceDependencies\": []\n  },\n  \"@hi3g/commitlint-config\": {\n    \"location\": \"packages/core/c
ommitlint-config\",\n    \"workspaceDependencies\": [\n      \"@hi3g/browserslist-config\",\n      \"@hi3g/lint-config\"\n    ],\n    \"mismatchedWorkspaceDependencies\": []\n  },\n  \"@hi3g/fonts\": {\n    \"location\": \"packages/core/fonts\",\n    \
"workspaceDependencies\": [\n      \"@hi3g/browserslist-config\",\n      \"@hi3g/lint-config\"\n    ],\n    \"mismatchedWorkspaceDependencies\": []\n  },\n  \"@hi3g/icons-flags\": {\n    \"location\": \"packages/core/icons-flags\",\n    \"workspaceDepe
ndencies\": [\n      \"@hi3g/browserslist-config\",\n      \"@hi3g/lint-config\"\n    ],\n    \"mismatchedWorkspaceDependencies\": []\n  },\n  \"@hi3g/icons\": {\n    \"location\": \"packages/core/icons\",\n    \"workspaceDependencies\": [\n      \"@hi
3g/browserslist-config\",\n      \"@hi3g/lint-config\"\n    ],\n    \"mismatchedWorkspaceDependencies\": []\n  },\n  \"@hi3g/lint-config\": {\n    \"location\": \"packages/core/lint-config\",\n    \"workspaceDependencies\": [],\n    \"mismatchedWorkspa
ceDependencies\": []\n  },\n  \"@hi3g/server-logger\": {\n    \"location\": \"packages/core/server-logger\",\n    \"workspaceDependencies\": [\n      \"@hi3g/lint-config\"\n    ],\n    \"mismatchedWorkspaceDependencies\": []\n  },\n  \"@hi3g/tre-se-app
-bridge\": {\n    \"location\": \"packages/core/tre-se-app-bridge\",\n    \"workspaceDependencies\": [\n      \"@hi3g/browserslist-config\",\n      \"@hi3g/lint-config\",\n      \"@hi3g/client-logger\"\n    ],\n    \"mismatchedWorkspaceDependencies\":
[]\n  },\n  \"@hi3g/tre-se-app\": {\n    \"location\": \"packages/tre-se-app\",\n    \"workspaceDependencies\": [\n      \"@hi3g/browserslist-config\",\n      \"@hi3g/lint-config\",\n      \"@hi3g/3style\",\n      \"@hi3g/analytics\",\n      \"@hi3g/ap
plication-insights\",\n      \"@hi3g/client-logger\",\n      \"@hi3g/icons\",\n      \"@hi3g/icons-flags\",\n      \"@hi3g/server-logger\",\n      \"@hi3g/tre-se-app-bridge\"\n    ],\n    \"mismatchedWorkspaceDependencies\": []\n  }\n}"}
```

`yarn workspaces info`:
```
{
  "@hi3g/3style-docs": {
    "location": "packages/3style-docs",
    "workspaceDependencies": [
      "@hi3g/browserslist-config",
      "@hi3g/lint-config",
      "@hi3g/3style",
      "@hi3g/icons"
    ],
    "mismatchedWorkspaceDependencies": []
  },
  "@hi3g/3style": {
    "location": "packages/core/3style",
    "workspaceDependencies": [
      "@hi3g/browserslist-config",
      "@hi3g/lint-config",
      "@hi3g/fonts",
      "@hi3g/icons"
    ],
    "mismatchedWorkspaceDependencies": []
  },
  "@hi3g/analytics": {
    "location": "packages/core/analytics",
    "workspaceDependencies": [
      "@hi3g/browserslist-config",
      "@hi3g/lint-config"
    ],
    "mismatchedWorkspaceDependencies": []
  },
  "@hi3g/application-insights": {
    "location": "packages/core/application-insights",
    "workspaceDependencies": [
      "@hi3g/lint-config",
      "@hi3g/server-logger"
    ],
    "mismatchedWorkspaceDependencies": []
  },
  "@hi3g/browserslist-config": {
    "location": "packages/core/browserslist-config",
    "workspaceDependencies": [
      "@hi3g/lint-config"
    ],
    "mismatchedWorkspaceDependencies": []
  },
  "@hi3g/logger-dev": {
    "location": "packages/core/client-logger/dev",
    "workspaceDependencies": [],
    "mismatchedWorkspaceDependencies": []
  },
  "@hi3g/client-logger": {
    "location": "packages/core/client-logger",
    "workspaceDependencies": [
      "@hi3g/browserslist-config",
      "@hi3g/lint-config"
    ],
    "mismatchedWorkspaceDependencies": []
  },
  "@hi3g/commitlint-config": {
    "location": "packages/core/commitlint-config",
    "workspaceDependencies": [
      "@hi3g/browserslist-config",
      "@hi3g/lint-config"
    ],
    "mismatchedWorkspaceDependencies": []
  },
  "@hi3g/fonts": {
    "location": "packages/core/fonts",
    "workspaceDependencies": [
      "@hi3g/browserslist-config",
      "@hi3g/lint-config"
    ],
    "mismatchedWorkspaceDependencies": []
  },
  "@hi3g/icons-flags": {
    "location": "packages/core/icons-flags",
    "workspaceDependencies": [
      "@hi3g/browserslist-config",
      "@hi3g/lint-config"
    ],
    "mismatchedWorkspaceDependencies": []
  },
  "@hi3g/icons": {
    "location": "packages/core/icons",
    "workspaceDependencies": [
      "@hi3g/browserslist-config",
      "@hi3g/lint-config"
    ],
    "mismatchedWorkspaceDependencies": []
  },
  "@hi3g/lint-config": {
    "location": "packages/core/lint-config",
    "workspaceDependencies": [],
    "mismatchedWorkspaceDependencies": []
  },
  "@hi3g/server-logger": {
    "location": "packages/core/server-logger",
    "workspaceDependencies": [
      "@hi3g/lint-config"
    ],
    "mismatchedWorkspaceDependencies": []
  },
  "@hi3g/tre-se-app-bridge": {
    "location": "packages/core/tre-se-app-bridge",
    "workspaceDependencies": [
      "@hi3g/browserslist-config",
      "@hi3g/lint-config",
      "@hi3g/client-logger"
    ],
    "mismatchedWorkspaceDependencies": []
  },
  "@hi3g/tre-se-app": {
    "location": "packages/tre-se-app",
    "workspaceDependencies": [
      "@hi3g/browserslist-config",
      "@hi3g/lint-config",
      "@hi3g/3style",
      "@hi3g/analytics",
      "@hi3g/application-insights",
      "@hi3g/client-logger",
      "@hi3g/icons",
      "@hi3g/icons-flags",
      "@hi3g/server-logger",
      "@hi3g/tre-se-app-bridge"
    ],
    "mismatchedWorkspaceDependencies": []
  }
}
```

**Comment by devshorts** [comment]
I'm not sure honestly, it sounds like there may be some other things printed to stdout when you run `yarn workspaces info --json` because all its doing is trying to parse text.  if you run the command in the root does anything else print to stdout? no warnings or extra information?

**Comment by mlenser** [comment]
Nope, just the above shows.

**Comment by mlenser** [comment]
At a glance `JSON.parse(JSON.parse(run("yarn workspaces info --json"))["data"]);` seems like it'd return the same thing as `yarn workspaces info`. Why get the json and then parse it and then parse the data part?

**Comment by devshorts** [comment]
Because the data part is a string encoded json. If you look at the test you’ll see.

**Comment by devshorts** [comment]
Can you try cloning the repo and running ytools in the sample folder? Curious what the difference here would be

**Comment by mlenser** [comment]
Hmm, can't get this repo to run `ytools`:
```
'ytools' is not recognized as an internal or external command, operable program or batch file.
```
I tried running compile first.

**Comment by devshorts** [comment]
@mlenser just do 

```
yarn compile
cd samples
node ../dist/index.js 
```

Let me publish an updated version where I use `yarn workspaces info -s` which gets rid of the stdout pollution that `yarn workspaces info` has (which is why I originally did the --json) version and see if that helps you

**Comment by mlenser** [comment]
With the latest as of 10 mins ago. Running `node ../dist/index.js` results in
```
(node:9804) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of null
    at run (PATH\ytools\dist\tools.js:20:26)
    at Object.yarnWorkspaceInfo (PATH\ytools\dist\tools.js:54:34)
    at detect (PATH\ytools\dist\index.js:27:31)
    at Object.<anonymous> (PATH\ytools\dist\index.js:127:1)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
```
pointing to
```
return result.stdout.toString().trim();
```

**Comment by devshorts** [comment]
@mlenser Ok, so I think the issue here has been that I had ytools set up to use the gitroot for its root automatically.  We need to do the following first:

```
yarn compile
cd samples
git init
git add --all . 
git commit -am "test"
<make any change to the samples package.json
../dist/index.js
```

This basically sets up the git root for the samples package and simulates a change in the git tree.  Then ytools will be able to find the workspace, the dependencies, AND the changed files list.

Can you try again? Sorry this is such a frustrating experience, still not sure what you're hitting yet!

**Comment by mlenser** [comment]
You're providing support for a potentially very useful tool, don't apologize. Thanks for doing so! :)

I checked out from scratch and followed the above and unfortunately got the same `TypeError: Cannot read property 'toString' of null` as above.

for the step:
> <make any change to the samples package.json

I changed the version in the package.json, but didn't commit.


I can have a coworker try tomorrow.

**Comment by devshorts** [comment]
@mlenser I did a fresh clone in a new folder and here is me running through the steps to evaluate the sample folder. It's more of just a sanity check that the underlying npm/yarn/git tooling are all sane.

You can see I compiled the root, went to the samples folder, initialized it as a git folder. committed all the stuff into it, made a modification to package.json with some whitespace (so that the package.json is still valid) and then ran the dist index. It spit out 

```
{
  "hoist1": {
    "name": "hoist1",
    "path": "packages/hoist1"
  },
  "nohoist": {
    "name": "nohoist",
    "path": "packages/nohoist"
  }
}
```
as changed because I made a change to `hoist` and `hoist1` depends on `nohoist`. If you run it with `-v` it spits out:

```
$ ../dist/index.js -v
Found config path of /Users/akropp/src/personal/ytools/samples/.ytools.js
processing hoist1...
processing hoist2...
processing nohoist...
File locations:
  -> packages/hoist1: packages/hoist1/package.json
Dirty projects by default: hoist1
  -> Marking nohoist dirty because it depends on hoist1
{"hoist1":{"name":"hoist1","path":"packages/hoist1"},"nohoist":{"name":"nohoist","path":"packages/nohoist"}}

```
At this point I'm very curious what the differences in our setups are! 

Anyways thanks for trooping on, looking forward to our next round :)
![ytools](https://user-images.githubusercontent.com/1799346/74784455-c68fc080-525c-11ea-9da8-ad0bd413522d.gif)

**Comment by devshorts** [comment]
@mlenser following up. On latest release of 1.0.11 do you still have issues?

**Comment by airtonix** [comment]
Reason why this happens is you're using Yarn 1.22, `yarn workspaces list` isn't a thing there. You need to use yarn 2. https://yarnpkg.com/cli/workspaces/list

**Comment by devshorts** [comment]
That’s not correct. This was on 1.x when the code was using workspaces info. Workspaces list was added well after this was reported and closed
